<a href="https://colab.research.google.com/github/noranzaki/AI---ML-project-/blob/main/Ai_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np                          
import matplotlib.pyplot as plt     

train=pd.read_csv('tmdb-movies (2).csv')
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10866 entries, 0 to 10865
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    10866 non-null  int64
 1   imdb_id               10856 non-null  object
 2   popularity            10866 non-null  float64
 3   original_title        10866 non-null  object
 4   cast                  10790 non-null  object
 5   homepage              2936 non-null   object
 6   director              10822 non-null  object
 7   tagline               8042 non-null   object
 8   keywords              9373 non-null   object
 9   overview              10862 non-null  object
 10  runtime               10866 non-null  int64
 11  genres                10843 non-null  object
 12  production_companies  9836 non-null   object
 13  release_date          10866 non-null  object
 14  vote_count            10866 non-null  int64
 15  vote_average          10866 non-null  float64
 16  release_year          10866 non-null  int64
 17  budget_adj            10866 non-null  float64
 18  revenue_adj           10866 non-null  float64
dtypes: float64(4), int64(4), object(11)
memory usage: 1.6+ MB

In [18]:
# Import label encoder
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
 
# Encode labels in columns
train['cast']= label_encoder.fit_transform(train['cast'])
train['homepage']= label_encoder.fit_transform(train['homepage'])
train['director']= label_encoder.fit_transform(train['director'])
train['tagline']= label_encoder.fit_transform(train['tagline'])
train['keywords']= label_encoder.fit_transform(train['keywords'])
train['genres']= label_encoder.fit_transform(train['genres'])
train['production_companies']= label_encoder.fit_transform(train['production_companies'])

# Net Profit Column
train['net_profit']=train['revenue_adj']-train['budget_adj']

In [19]:
train.corr()

,id,popularity,cast,homepage,director,tagline,keywords,runtime,genres,production_companies,vote_count,vote_average,release_year,budget_adj,revenue_adj,net_profit
id,1.000000,-0.014350,-0.005470,-0.121467,-0.040560,0.083869,0.125397,-0.088360,0.169499,-0.006800,-0.035551,-0.058363,0.511364,-0.189015,-0.138477,-0.108166
popularity,-0.014350,1.000000,-0.002405,-0.184321,-0.003511,-0.124662,-0.097738,0.139033,-0.074022,0.005763,0.800828,0.209511,0.089801,0.513550,0.609083,0.562834
cast,-0.005470,-0.002405,1.000000,0.014265,0.037157,0.003765,0.007820,-0.018728,-0.024385,0.024698,-0.003026,0.028439,-0.021627,0.005359,0.021353,0.023196
homepage,-0.121467,-0.184321,0.014265,1.000000,0.000888,0.035845,0.030227,-0.001669,-0.012256,-0.001057,-0.219208,-0.110501,-0.297506,-0.115577,-0.130970,-0.119614
director,-0.040560,-0.003511,0.037157,0.000888,1.000000,0.007424,-0.002323,0.007818,-0.000340,0.001396,0.001552,0.030363,-0.027229,0.023617,0.016529,0.012621
tagline,0.083869,-0.124662,0.003765,0.035845,0.007424,1.000000,0.104039,-0.071793,0.009207,0.061964,-0.106881,-0.002233,0.089677,-0.143568,-0.114327,-0.092722
keywords,0.125397,-0.097738,0.007820,0.030227,-0.002323,0.104039,1.000000,-0.054421,0.025919,0.049376,-0.080651,-0.050295,0.091443,-0.104302,-0.081894,-0.066017
runtime,-0.088360,0.139033,-0.018728,-0.001669,0.007818,-0.071793,-0.054421,1.000000,0.014846,-0.026089,0.163278,0.156835,-0.117204,0.221114,0.175676,0.142339
genres,0.169499,-0.074022,-0.024385,-0.012256,-0.000340,0.009207,0.025919,0.014846,1.000000,-0.038699,-0.079168,-0.030025,0.066111,-0.155751,-0.104936,-0.078537
production_companies,-0.006800,0.005763,0.024698,-0.001057,0.001396,0.061964,0.049376,-0.026089,-0.038699,1.000000,0.010322,0.026186,-0.026554,0.012463,0.030394,0.031693
vote_count,-0.035551,0.800828,-0.003026,-0.219208,0.001552,-0.106881,-0.080651,0.163278,-0.079168,0.010322,1.000000,0.253823,0.107948,0.587051,0.707942,0.656885
vote_average,-0.058363,0.209511,0.028439,-0.110501,0.030363,-0.002233,-0.050295,0.156835,-0.030025,0.026186,0.253823,1.000000,-0.117632,0.093039,0.193085,0.197537
release_year,0.511364,0.089801,-0.021627,-0.297506,-0.027229,0.089677,0.091443,-0.117204,0.066111,-0.026554,0.107948,-0.117632,1.000000,0.016793,-0.066256,-0.081132
budget_adj,-0.189015,0.513550,0.005359,-0.115577,0.023617,-0.143568,-0.104302,0.221114,-0.155751,0.012463,0.587051,0.093039,0.016793,1.000000,0.646607,0.472901
revenue_adj,-0.138477,0.609083,0.021353,-0.130970,0.016529,-0.114327,-0.081894,0.175676,-0.104936,0.030394,0.707942,0.193085,-0.066256,0.646607,1.000000,0.977916
net_profit,-0.108166,0.562834,0.023196,-0.119614,0.012621,-0.092722,-0.066017,0.142339,-0.078537,0.031693,0.656885,0.197537,-0.081132,0.472901,0.977916,1.000000

In [20]:
#Dropping useless columns
train = train.drop(columns = ['id'],axis=1)
train = train.drop(columns = ['imdb_id'],axis=1)
train = train.drop(columns = ['original_title'],axis=1)
train = train.drop(columns = ['homepage'],axis=1)
train = train.drop(columns = ['tagline'],axis=1)
train = train.drop(columns = ['keywords'],axis=1)
train = train.drop(columns = ['overview'],axis=1)
train = train.drop(columns = ['runtime'],axis=1)
train = train.drop(columns = ['release_year'],axis=1)
train = train.drop(columns = ['release_date'],axis=1)
train = train.drop(train[train.budget_adj <= 0].index,axis=0) 
train = train.drop(train[train.revenue_adj <= 0].index,axis=0)

In [9]:
#Checking for null values
train.isnull().sum()

popularity              0
cast                    0
director                0
genres                  0
production_companies    0
vote_count              1
vote_average            1
budget_adj              1
revenue_adj             1
net_profit              1
dtype: int64

In [21]:
#Checking for Duplicates
train.duplicated().sum()

1

In [22]:
train.drop_duplicates(inplace=True)

In [23]:
train

,popularity,cast,director,genres,production_companies,vote_count,vote_average,budget_adj,revenue_adj,net_profit
0,32.985763,1739,899,116,6823,5562,6.5,1.379999e+08,1.392446e+09,1.254446e+09
1,28.419936,10084,1681,116,6923,6185,7.1,1.379999e+08,3.481613e+08,2.101614e+08
2,13.112507,9278,4130,578,5788,2480,6.3,1.012000e+08,2.716190e+08,1.704191e+08
3,11.173104,3697,1942,114,3575,5292,7.5,1.839999e+08,1.902723e+09,1.718723e+09
4,9.335014,10331,2058,224,6701,2947,7.3,1.747999e+08,1.385749e+09,1.210949e+09
...,...,...,...,...,...,...,...,...,...,...
10822,0.670274,2969,3444,984,1103,74,7.5,5.038511e+07,2.266436e+08,1.762585e+08
10828,0.402730,7919,169,1649,6533,46,6.3,2.015404e+07,8.733419e+07,6.718015e+07
10829,0.395668,5123,1883,362,4648,36,6.9,3.125892e+07,4.030809e+07,9.049166e+06
10835,0.299911,9619,4138,81,6383,28,7.0,8.061618e+07,1.343603e+08,5.374412e+07
10848,0.207257,9485,3980,573,6229,42,6.7,3.436265e+07,8.061618e+07,4.625353e+07

In [24]:
#Normalizing Values Function
def normalize():
    global train
    result = train.copy()
    for feature_name in train.columns:
        max_value = train[feature_name].max()
        min_value = train[feature_name].min()
        result[feature_name] = (train[feature_name] - min_value) / (max_value - min_value)
    train= result

In [25]:
normalize()

In [26]:
train

,popularity,cast,director,genres,production_companies,vote_count,vote_average,budget_adj,revenue_adj,net_profit
0,1.000000,0.162079,0.177423,0.056919,0.916443,0.569027,0.693548,0.324706,0.492531,0.527286
1,0.861577,0.940748,0.331754,0.056919,0.929876,0.632879,0.790323,0.324706,0.123150,0.197239
2,0.397500,0.865541,0.815078,0.283611,0.777405,0.253152,0.661290,0.238118,0.096076,0.184678
3,0.338703,0.344779,0.383264,0.055937,0.480118,0.541355,0.854839,0.432941,0.673024,0.674021
4,0.282977,0.963796,0.406157,0.109912,0.900054,0.301015,0.822581,0.411294,0.490162,0.513539
...,...,...,...,...,...,...,...,...,...,...
10822,0.020287,0.276850,0.679692,0.482826,0.148039,0.006559,0.854839,0.118553,0.080168,0.186524
10828,0.012176,0.738733,0.033353,0.809127,0.877485,0.003690,0.661290,0.047421,0.030892,0.152050
10829,0.011962,0.477839,0.371620,0.177625,0.624261,0.002665,0.758065,0.073550,0.014258,0.133677
10835,0.009059,0.897359,0.816657,0.039745,0.857335,0.001845,0.774194,0.189685,0.047525,0.147803
10848,0.006250,0.884856,0.785475,0.281158,0.836647,0.003280,0.725806,0.080853,0.028515,0.145436

In [27]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3854 entries, 0 to 10848
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   popularity            3854 non-null   float64
 1   cast                  3854 non-null   float64
 2   director              3854 non-null   float64
 3   genres                3854 non-null   float64
 4   production_companies  3854 non-null   float64
 5   vote_count            3854 non-null   float64
 6   vote_average          3854 non-null   float64
 7   budget_adj            3854 non-null   float64
 8   revenue_adj           3854 non-null   float64
 9   net_profit            3854 non-null   float64
dtypes: float64(10)
memory usage: 331.2 KB

In [28]:
#Splitting Data to train and test
X= train.drop(['budget_adj','revenue_adj','net_profit'],axis=1)
Y= train['net_profit']
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.2,random_state=3)

#Reshaping
Y_train = np.array(Y_train)
Y_train = Y_train.reshape(Y_train.shape[0], 1)

Y_test = np.array(Y_test)
Y_test = Y_test.reshape(Y_test.shape[0], 1)

X_train = np.vstack((np.ones((X_train.shape[0], )), X_train.T)).T
X_test = np.vstack((np.ones((X_test.shape[0], )), X_test.T)).T

In [29]:
def model(X, Y, learning_rate, iteration):
  m = Y.size
  theta = np.zeros((X.shape[1], 1))
  cost_list = []
  for i in range(iteration):
    y_pred = np.dot(X, theta)
    cost = (1/(2*m))*np.sum(np.square(y_pred - Y))
    d_theta = (1/m)*np.dot(X.T, y_pred - Y)
    theta = theta - learning_rate*d_theta
    cost_list.append(cost)
    # to print the cost for 10 times
    if(i%(iteration/10) == 0):
      print("Cost is :", cost)
  return theta, cost_list

In [30]:
iteration = 10000
learning_rate = 0.00005
theta, cost_list = model(X_train, Y_train, learning_rate = learning_rate, iteration =iteration)

Cost is : 0.014510038507946446
Cost is : 0.011730346280708692
Cost is : 0.009561367124671314
Cost is : 0.00786884533210153
Cost is : 0.006548039506365321
Cost is : 0.005517234236342291
Cost is : 0.004712678142235767
Cost is : 0.00408463472414937
Cost is : 0.003594301378660334
Cost is : 0.0032114057282943754

In [31]:
y_pred = np.dot(X_test, theta)
error = (1/X_test.shape[0])*np.sum(np.abs(y_pred - Y_test))

In [32]:
print("Test error is :", error*100, "%")
print("Test Accuracy is :", (1- error)*100, "%")

Test error is : 5.149277267651971 %
Test Accuracy is : 94.85072273234803 %